name: Deploy QA

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string

run-name: deploy-qa-pr-${{ inputs.pr_number }}

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR Number
        run: echo "Deploying QA for PR #${{ inputs.pr_number }}"
